# Generated by Django 6.0.3 on 2026-04-04 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatColonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_colonia', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CatDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_direccion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TicketAyuda',
            fields=[
                ('folio', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=150)),
                ('asunto', models.CharField(blank=True, max_length=150, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Nuevo', max_length=50)),
                ('colonia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.catcolonia')),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.catdireccion')),
            ],
        ),
    ]
