# Generated by Django 6.0.3 on 2026-04-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketayuda_latitud_ticketayuda_longitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketayuda',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticketayuda',
            name='folio',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
