# Generated by Django 6.0.3 on 2026-04-08 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketayuda_agente_asignado_ticketayuda_evidencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilagente',
            name='rol',
            field=models.CharField(choices=[('Director', 'Director de Área'), ('Subdirector', 'Subdirector / Jefe de Departamento'), ('Coordinador', 'Coordinador / Cuadrilla Operativa')], default='Coordinador', max_length=50),
        ),
        migrations.AddField(
            model_name='ticketayuda',
            name='coordinador_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_como_coordinador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketayuda',
            name='director_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_como_director', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketayuda',
            name='subdirector_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_como_subdirector', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TareaTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('completada', models.BooleanField(default=False)),
                ('evidencia_tarea', models.FileField(blank=True, null=True, upload_to='evidencias_tareas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('ejecutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='tickets.ticketayuda')),
            ],
        ),
    ]
