# Generated by Django 6.0.3 on 2026-04-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_perfilagente_rol_ticketayuda_coordinador_asignado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopacisyDelegados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellidos', models.CharField(max_length=255)),
                ('Seccion', models.CharField(max_length=255)),
            ],
        ),
    ]
