# Generated by Django 6.0.3 on 2026-04-16 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_copacisydelegados'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketayuda',
            name='gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.copacisydelegados', verbose_name='Gestor de la Solicitud (Opcional)'),
        ),
    ]
