# Generated by Django 6.0.3 on 2026-04-21 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticketayuda_gestor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketayuda',
            name='domicilio',
        ),
        migrations.AddField(
            model_name='ticketayuda',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno (Opcional)'),
        ),
        migrations.AddField(
            model_name='ticketayuda',
            name='apellido_paterno',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Apellido Paterno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketayuda',
            name='calle',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Calle/Avenida'),
        ),
        migrations.AddField(
            model_name='ticketayuda',
            name='numero_exterior',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. Exterior'),
        ),
        migrations.AddField(
            model_name='ticketayuda',
            name='numero_interior',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. Interior (Opcional)'),
        ),
        migrations.AlterField(
            model_name='ticketayuda',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.catdireccion', verbose_name='Dependencia'),
        ),
        migrations.AlterField(
            model_name='ticketayuda',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre(s)'),
        ),
    ]
