# Generated by Django 6.0.3 on 2026-04-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_remove_ticketayuda_domicilio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketayuda',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
