# Generated by Django 6.0.3 on 2026-04-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticketayuda_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketayuda',
            name='gestor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Gestor (Dejar en blanco si es Ciudadano Directo)'),
        ),
    ]
