# Generated by Django 6.0.3 on 2026-04-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_ticketayuda_gestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketayuda',
            name='numero_ocp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de OCP'),
        ),
    ]
