# Generated by Django 6.0.3 on 2026-04-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticketayuda_numero_ocp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketayuda',
            name='via_entrada',
            field=models.CharField(choices=[('Ciudadano', 'Ciudadano'), ('Oficio', 'Oficio')], default='Ciudadano', max_length=20, verbose_name='Vía de Entrada'),
        ),
    ]
