# Generated by Django 6.0.3 on 2026-04-28 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_ticketayuda_via_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketayuda',
            name='calle_ciudadano',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Calle del Ciudadano'),
        ),
        migrations.AddField(
            model_name='ticketayuda',
            name='colonia_ciudadano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_como_ciudadano', to='tickets.catcolonia', verbose_name='Colonia del Ciudadano'),
        ),
        migrations.AddField(
            model_name='ticketayuda',
            name='numero_exterior_ciudadano',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. Exterior Ciudadano'),
        ),
        migrations.AddField(
            model_name='ticketayuda',
            name='numero_interior_ciudadano',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Núm. Interior Ciudadano'),
        ),
    ]
