# Generated by Django 6.0.3 on 2026-04-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_ticketayuda_calle_ciudadano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketayuda',
            name='via_entrada',
            field=models.CharField(choices=[('Ciudadano', 'Ciudadano'), ('Oficio', 'Oficio'), ('Miercoles Ciudadano', 'Miercoles Ciudadano')], default='Ciudadano', max_length=20, verbose_name='Vía de Entrada'),
        ),
    ]
