# Generated by Django 6.0.3 on 2026-05-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_ticketayuda_via_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilagente',
            name='es_coordinador_especial',
            field=models.BooleanField(default=False, verbose_name='¿Es Coordinador Especial? (Puede agregar acciones extra)'),
        ),
        migrations.AlterField(
            model_name='ticketayuda',
            name='via_entrada',
            field=models.CharField(choices=[('Ciudadano', 'Ciudadano'), ('Oficio', 'Oficio'), ('MIÉRCOLES CIUDADANO', 'MIÉRCOLES CIUDADANO')], default='Ciudadano', max_length=20, verbose_name='Vía de Entrada'),
        ),
    ]
