# Generated by Django 6.0.3 on 2026-05-11 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_perfilagente_es_coordinador_especial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias_tareas_multiples/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_multiples', to='tickets.tareaticket')),
            ],
        ),
    ]
