# Generated by Django 6.0.3 on 2026-05-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_evidenciatarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareaticket',
            name='descripcion',
            field=models.CharField(max_length=600),
        ),
    ]
