# Generated by Django 6.0.3 on 2026-08-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_tareaticket_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareaticket',
            name='descripcion',
            field=models.CharField(max_length=2000),
        ),
    ]
